version: "3"

services:
  postgis:
    container_name: db_tracker
    image: kartoza/postgis
    volumes:
      - "./db:/var/lib/postgresql"
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    network_mode: host

  # pgadmin:
  #   container_name: pgadmin_mortgage
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"

  # redis:
  #   image: redis:latest
  #   network_mode: host

volumes:
  tracker-pgdata:
