version: "3"

services:
  postgis:
    container_name: db_tracker
    image: kartoza/postgis
    volumes:
      - "./db:/var/lib/postgresql"
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=tracker
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    network_mode: host

  # server:
  #   container_name: server_tracker
  #   build:
  #     context: "./server"
  #     dockerfile: Dockerfile.server
  #   depends_on:
  #     - postgis
  #   environment:
  #     - DATABASE_URL=postgis://tracker:tracker@127.0.0.1:5432/tracker
  #   ports:
  #     - "8000:8000"
  #   network_mode: host

  # client:
  #   container_name: client_tracker
  #   build:
  #     context: "./client"
  #     dockerfile: Dockerfile.client
  #   volumes:
  #     - type: bind
  #       source: "./client/src"
  #       target: /cleint/src
  #   ports:
  #     - "3000:3000"
  #   network_mode: host

  tracker:
    container_name: test_tracker
    build:
      context: "./test"
      dockerfile: Dockerfile.test
    volumes:
      - type: bind
        source: "./test/public"
        target: /test/public
    ports:
      - "5000:5000"
    network_mode: host

volumes:
  tracker-pgdata:
