# Generated by Django 3.2.8 on 2021-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_limit_violations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
