# Generated by Django 3.2.8 on 2021-11-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_limit_violations', '0002_alter_speedviolation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date'),
        ),
    ]
