# Generated by Django 3.2.8 on 2022-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_limit_violations', '0003_alter_speedviolation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedviolation',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
    ]
