# Generated by Django 3.1.4 on 2021-09-29 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('speed', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
            ],
        ),
    ]
