# Generated by Django 3.1.4 on 2021-10-08 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='speed',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='imei',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rfid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speed', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('course', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='vehicles.vehicle')),
            ],
        ),
    ]
