# Generated by Django 3.1.4 on 2021-10-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20211008_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='imei',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rfid',
        ),
    ]
