# Generated by Django 3.2.8 on 2021-11-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20211021_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
