# Generated by Django 3.2.8 on 2022-01-31 09:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_received_from_tracker', models.DateTimeField(blank=True, default=None, null=True)),
                ('time_sent_to_display', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
