# Generated by Django 3.2.8 on 2021-10-25 13:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speed_limit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedlimit',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326),
        ),
    ]
