# Generated by Django 3.2.8 on 2021-10-25 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speed_limit', '0002_speedlimit_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedlimit',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
